language: c

sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      env: OSNAME="linux"
      # Linux Ubuntu Trusty
    - os: osx
      osx_image: xcode9
      env: OSNAME="osx" OSVERSION="10.13" OSBUILD="brew"
      # Apple OSX 10.13 High Sierra
    - os: osx
      osx_image: xcode8.3
      env: OSNAME="osx" OSVERSION="10.12" OSBUILD="brew"
      # Apple OSX 10.12 Sierra
    - os: osx
      osx_image: xcode8
      env: OSNAME="osx" OSVERSION="10.11" OSBUILD="brew"
      # Apple OSX 10.11 El Capitan
    - os: osx
      osx_image: xcode6.4
      env: OSNAME="osx" OSVERSION="10.10 10.9" OSBUILD="sources"
      # Apple OSX 10.10 Yosemite
      # Apple OSX 10.9 Mavericks

compiler: gcc

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

addons:
  apt:
    packages:
      - automake
      - autoconf
      - libtool
      - m4
      - gettext

before_install:
  - chmod a+x ./.travis/before_install.sh
  - ./.travis/before_install.sh

script:
  - ./autogen.sh
  - make all

#
#after_success:
#  - chmod a+x ./.travis/after_success.sh
#  - ./.travis/after_success.sh

# Deploy Release Package
#deploy:
#  provider: releases
#  api_key:
#    secure:
#  file:
#  skip_clean: true
#  on:
#    repo: haakonnessjoen/MAC-Telnet
#    tags: true

after_script:
  - set +e
