language: c

sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      env: OSNAME="linux"
    - os: osx
      osx_image: xcode9
      env: OSNAME="osx" OSVERSION="10.13" OSBUILD="brew"
    - os: osx
      osx_image: xcode8.3
      env: OSNAME="osx" OSVERSION="10.12" OSBUILD="brew"
    - os: osx
      osx_image: xcode8
      env: OSNAME="osx" OSVERSION="10.11" OSBUILD="brew"
    - os: osx
      osx_image: xcode6.4
      env: OSNAME="osx" OSVERSION="10.10 10.9" OSBUILD="sources"

compiler: gcc

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

addons:
  apt:
    packages:
      - automake
      - autoconf
      - libtool
      - m4
      - gettext

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then chmod a+x ./travis-osx.sh;   ./travis-osx.sh;   fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod a+x ./travis-linux.sh; ./travis-linux.sh; fi

script:
  - ./autogen.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then ./configure --disable-nls; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure;               fi
  - make all
